[project]
name = "GlennOPT"
version = "1.5.5"
description = "Multi and single objective optimization tool for cfd/computer simulations."
authors = [
    {name = "Paht Juangphanich", email = "paht.juangphanich@nasa.gov"},
]
requires-python = ">3.11"
dependencies = [
    "matplotlib>3.3.2",
    "numpy",
    "pandas",
    "psutil",
    "pyDOE3",
    "dataclasses_json",
    "scipy",
    "tqdm",
    "scikit-learn",
    "pyyaml",
]

[project.optional-dependencies]
ml = ["torch"]

[dependency-groups]
docs = [
    "sphinx",
    "sphinx_rtd_theme",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["glennopt"]
